export enum Subscriptions {
  ONLINE_STATUS = "ONLINE_STATUS",
  NEW_COMMENT = "NEW_COMMENT",
  PROJECT_CONTENT_CHANGE = "PROJECT_CONTENT_CHANGE",
  PROJECT_ONLINE_STATUS = "PROJECT_ONLINE_STATUS",
  UPLOADED_FILE_PROCESSED = "UPLOADED_FILE_PROCESSED",
  PEAK_WAVEFORM_ANALYZED = "PEAK_WAVEFORM_ANALYZED",
}