name: johannesklauss/syra

interfaces:
  admin-fe: ${{ services.admin-fe.interfaces.main.url }}
  daw-fe: ${{ services.daw-fe.interfaces.main.url }}
  live-fe: ${{ services.live-fe.interfaces.main.url }}

services:
  admin-fe:
    build:
      context: ./syra-admin-fe
    description: Administrative platform for SYRA Live
    language: node
    interfaces:
      main: 8080
    environment:
      PORT: ${{ services.admin-fe.interfaces.main.port }}
      LIVE_GQL_ADDR:

  api-gateway:
    build:
      context: ./syra-api-gateway
    description: Service to handle all incoming API requests and session auths.
    language: node
    interfaces:
      main: 8080
    environment:
      PORT: ${{ services.api-gateway.interfaces.main.port }}

  api-gateway-db:
    image: library/redis:latest
    description: Session database
    interfaces:
      postgres:
        port: 6379
        protocol: resp
    environment:
      REDIS_PASSWORD: ${{ parameters.API_GATEWAY_DB_PASSWORD }}
      REDIS_REPLICATION_MODE: ${{ parameters.API_GATEWAY_DB_REPLICATION_MODE }}

  auth-api:
    build:
      context: ./syra-auth-api
    description: Service that handles authorization for service requests
    interfaces:
      main:
        port: 8080
        protocol: tcp
    debug:
      context: ./syra-auth-api
      command: npm run start:dev
      volumes:
        src:
          host_path: ./
          mount_path: /usr/src/app/src/

  daw-fe:
    build:
      context: ./syra-daw-fe
    description: SYRA DAW
    language: node
    interfaces:
      main: 8080
    environment:
      PORT: ${{ services.daw-fe.interfaces.main.port }}

  live-db:
    image: postgres:12
    description: Database for SYRA Live social media platform
    interfaces:
      postgres:
        port: 5432
        protocol: postgres
    environment:
      POSTGRES_USER: ${{ parameters.LIVE_DB_USER }}
      POSTGRES_PASSWORD: ${{ parameters.LIVE_DB_PASSWORD }}
      POSTGRES_DB: ${{ parameters.LIVE_DB_DB }}

  live-fe:
    build:
      context: ./syra-live-fe
    description: SYRA Live social media platform
    language: node
    interfaces:
      main: 8080
    environment:
      PORT: ${{ services.live-fe.interfaces.main.port }}
      LIVE_GQL_ADDR:

  live-gql:
    build:
      context: ./syra-live-gql
    description: Service that handles authorized GraphQL requests for SYRA Live
    interfaces:
      main:
        port: 8080
        protocol: tcp
    debug:
      context: ./syra-live-gql
      command: npm run start:dev
      volumes:
        src:
          host_path: ./
          mount_path: /usr/src/app/src/
    environment:
      LIVE_DB_URL: postgresql://${{ parameters.LIVE_DB_USER }}:${{ parameters.LIVE_DB_PASSWORD }}@${{ services.live-db.interfaces.main.host }}:${{ services.live-db.interfaces.main.port }}/${{ parameters.LIVE_DB_DB }}