version: "3.8"

services:
  syra-auth-session-db:
    container_name: syra-auth-session-db
    image: library/redis:latest
    command: "redis-server --requirepass ${API_GATEWAY_DB_PASSWORD}"
    ports:
      - "6379:6379"
    volumes:
      - ./syra-auth-session-db/redis-data:/var/lib/redis
      - ./syra-auth-session-db/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - webnet
    healthcheck:
      test: ["CMD-SHELL", "redis-cli info"]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      - "REDIS_PASSWORD=${API_GATEWAY_DB_PASSWORD}"
      - "REDIS_REPLICATION_MODE=${API_GATEWAY_DB_REPLICATION_MODE}"
    env_file:
      - .env

  syra-daw-fe:
    stdin_open: true
    container_name: syra-daw-fe
    build:
      context: ./syra-daw-fe
    networks:
      - webnet
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - "/syra-daw-fe/node_modules"
      - "./syra-daw-fe:/syra-daw-fe"

  syra-live-db:
    container_name: syra-live-db
    image: postgres:12
    networks:
      - webnet
    environment:
      - "POSTGRES_USER=${LIVE_DB_USER}"
      - "POSTGRES_PASSWORD=${LIVE_DB_PASSWORD}"
      - "POSTGRES_DB=${LIVE_DB_DB}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LIVE_DB_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./syra-live-db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  syra-live-gql:
    stdin_open: true
    container_name: syra-live-gql
    build:
      context: ./syra-live-gql
      target: development
    command: yarn start:dev
    networks:
      - webnet
    depends_on:
      - syra-live-db
      - syra-auth-session-db
    ports:
      - "4020:3000"
    volumes:
      - "./syra-live-gql:/syra-live-gql"
      - "/syra-live-gql/node_modules"
    env_file:
      - .env

  syra-live-fe:
    stdin_open: true
    container_name: syra-live-fe
    build:
      context: ./syra-live-fe
    networks:
      - webnet
    depends_on:
      - syra-live-gql
    ports:
      - "8000:3000"
      - "6016:6006"
    volumes:
      - "/syra-live-fe/node_modules"
      - "./syra-live-fe:/syra-live-fe"
    env_file:
      - .env

  syra-admin-fe:
    stdin_open: true
    container_name: syra-admin-fe
    build:
      context: ./syra-admin-fe
    networks:
      - webnet
    depends_on:
      - syra-live-gql
    ports:
      - "8010:3000"
    volumes:
      - "/syra-admin-fe/node_modules"
      - "./syra-admin-fe:/syra-admin-fe"
    env_file:
      - .env

networks:
  webnet:

volumes:
  pgdata:
  redis-data: