version: "3.8"

services:
  syra-redis-cluster:
    container_name: syra-redis-cluster
    image: library/redis:latest
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/var/lib/redis
    networks:
      - webnet
    healthcheck:
      test: ["CMD-SHELL", "redis-cli info"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  webnet:

volumes:
  redis-data: