kind: Deployment
apiVersion: apps/v1
metadata:
  name: syra-live-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: syra-live-fe
  template:
    metadata:
      labels:
        app: syra-live-fe
    spec:
      containers:
        - name: syra-live-fe
          image: registry.digitalocean.com/syra-do/services_syra-live-gql
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: registry-syra-do
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: syra-live-fe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 3000
  selector:
    app: syra-live-fe