name: examples/srvc-api
description: Stateful GraphQL endpoint talking to a PostgreSQL database
keywords:
  - api
  - graphql
  - postgres
  - stateful
  - nestjs
parameters:
  LOG_LEVEL:
    description: "(one of: off, trace, error, warn, info, debug)"
    default: info
  DB_NAME: test
services:
  my-database:
    image: postgres:11
    interfaces:
      postgres:
        port: 5432
        protocol: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  payments-api:
    image: registry.architect.io/examples/react-demo/api:latest
      interfaces:
        api: 8081
      environment:
        LOG_LEVEL: ${{ parameters.LOG_LEVEL }}
        DB_ADDR: ${{ services.my-database.interfaces.postgres.url }}/${{ parameters.DB_NAME }}
        DB_USER: postgres
        DB_PASS: secret
  frontend:
    image: registry.architect.io/examples/react-demo/frontend:latest
    interfaces:
      web: 8080
    environment:
      API_ADDR: ${{ services.payments-api.interfaces.api.url }}
interfaces:
  demo:
    description: Primary access point to the react demo component
    url: ${{ services.frontend.interfaces.web.url }}