name: Deploy mainline

env:
  ARCHITECT_EMAIL: ${{ secrets.ARCHITECT_EMAIL }}
  ARCHITECT_PASSWORD: ${{ secrets.ARCHITECT_PASSWORD }}
  ARCHITECT_ACCOUNT: ${{ secrets.ARCHITECT_ACCOUNT }}
  MAINLINE_TAG_NAME: latest

on:
  push:
    branches:
      - master

jobs:
  architect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tests
        run: echo "Run your tests here"
      - name: install architect
        run: npm install -g @architect-io/cli
      - name: login
        run: architect login # credentials provided by envs ARCHITECT_EMAIL/ARCHITECT_PASSWORD
      - name: Tag architect component
        run: |
          architect register --tag ${{ env.MAINLINE_TAG_NAME }} ./services/architect.yml
      - name: deploy to staging
        run: |
          architect deploy --environment staging