name: Deploy to production

env:
  ARCHITECT_EMAIL: ${{ secrets.ARCHITECT_EMAIL }}
  ARCHITECT_PASSWORD: ${{ secrets.ARCHITECT_PASSWORD }}
  ARCHITECT_ACCOUNT: ${{ secrets.ARCHITECT_ACCOUNT }}

on:
  release:
    types:
      - published
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  architect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install architect
        run: yarn add @architect-io/cli -W
      - name: login
        run: yarn run architect login -e $ARCHITECT_EMAIL -p $ARCHITECT_PASSWORD
      - name: Tag architect component
        run: yarn run architect register --tag ${{ github.ref }} ./services/architect.yml
      - name: deploy to production
        run: |
          yarn run architect deploy --environment production