name: Architect Destroy Preview

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  architect_destroy_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - name: Architect Destroy Preview
        uses: architect-team/destroy-preview@v1.0.1
        with:
          email: ${{ secrets.ARCHITECT_EMAIL }}
          password: ${{ secrets.ARCHITECT_PASSWORD }}
          account: ${{ secrets.ARCHITECT_ACCOUNT }}
          environment: preview-${{ github.event.number }}
          component_name: syra
          component_file: ./services/architect.yml