name: Architect Create Preview

on:
  pull_request:
    branches:
      - preview

jobs:
  architect_create_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Architect Create Preview
        uses: architect-team/create-preview@v1.0.1
        with:
          email: ${{ secrets.ARCHITECT_EMAIL }}
          password: ${{ secrets.ARCHITECT_PASSWORD }}
          account: ${{ secrets.ARCHITECT_ACCOUNT }}
          environment: preview-${{ github.event.number }}
          platform: ${{ secrets.ARCHITECT_PLATFORM }}
          component_name: syra
          component_file: ./services/architect.yml