name: Release Publish

on:
  release:
    types:
      - published
    branches:
      - release

jobs:
  # Push image to Digital Ocean Image Registry.
  digital_ocean:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DO registry
        run: doctl registry login

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build and push Docker images to DO Registry
        run: |
          COMPONENTS=$(find services/syra-*/Dockerfile)

          for CMP in $COMPONENTS
          do
            IMAGE_NAME=$(dirname $CMP)
            IMAGE_ID=registry.digitalocean.com/syra-do/$IMAGE_NAME

            echo build and push $IMAGE_NAME:${{ steps.get_version.outputs.VERSION }}

            docker build $IMAGE_NAME --tag $(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]'):${{ steps.get_version.outputs.VERSION }}
            docker push $(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]'):${{ steps.get_version.outputs.VERSION }}

            echo "$IMAGE_NAME done! \n\n"
          done