name: Release CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - release

env:
  CI: "true"

jobs:
  # Push image to Github Image Registry.
  build_images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Slug Action
        uses: rlespinasse/github-slug-action@3.3.0

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker images to GH Registry
        if: ${{ env.GITHUB_REF_SLUG }} === "release"
        run: |
          REF=$(git rev-parse --short HEAD)
          COMPONENTS=$(find services/syra-*/Dockerfile)

          for CMP in $COMPONENTS
          do
            IMAGE_NAME=$(dirname $CMP)

            echo build $IMAGE_NAME:$REF

            docker build --build-arg LIVE_DB_URL ${{ secrets.LIVE_DB_URL }} $IMAGE_NAME --tag $REF

            echo "$IMAGE_NAME done! \n\n"
          done